[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts",
    "@account-abstraction/=lib/account-abstraction",
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
# All available network keywords:
# https://github.com/foundry-rs/forge-std/blob/f73c73d2018eb6a111f35e4dae7b4f27401e9421/src/StdChains.sol#L180-L226
base_goerli = "https://goerli.base.org"
